export const SHOW_LOADING = 'COMMENTS/SHOW_LOADING';
export const HIDE_LOADING = 'COMMENTS/HIDE_LOADING';
export const LOAD_COMMENTS_SUCCESS = 'COMMENTS/LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_ERROR = 'COMMENTS/LOAD_COMMENTS_ERROR';
